### ISSUE TITLE
aboId nicht übernommen

### ISSUE THREAD

**Issue by Paredroi** [fz72/read_insa_tickets#1]
Hallo fz72, ich wollte das Skript unter Windows ausprobieren und da gabs zunächst den Fehler, dass die "aboId" nicht übernommen worden ist. Liegt das vlt. daran, dass das "I" großgeschrieben ist, später aber mit kleinem "i" abgefragt wird?
read -p "Abo Id($aboid_file):" **aboId**
**aboid**="$aboid_file"

**Comment by fz72** [comment]
Hallo Paredroi, das kann gut damit zusammenhängen. Hast du mal probiert ob es funktioniert wenn du aboid mit kleinem I im Skript anpasst? Ich hab den Tippfehler auch soeben korrigiert.
Ich habe das Skript nur unter Linux getestet. Ich kann also nicht sagen ob es unter Windows zu Problemen führt.

**Comment by Paredroi** [comment]
Top danke, damit kann man den Punkt hier als erledigt markieren.
