### ISSUE TITLE
Skript unter Windows

### ISSUE THREAD

**Issue by Paredroi** [fz72/read_insa_tickets#2]
Außerdem habe ich irgendwie ziemliche Probleme damit, das Skript unter Windows auszuführen. Ich habe mir dafür Cygwin installiert (nachdem es mit win-bash irgendwie gar nicht ging). Trotzdem zeigt er mir nur Fehler:

```
$ '/cygdrive/c/Users/xxx/read_and_save_tickets.sh'
/cygdrive/c/Users/xxx/read_and_save_tickets.sh: line 18: auth.txt: No such file or directory
Abo Id():1234
Email():xxx@xxx.de
kvpid():HSB
Request: https://deutschlandticket.insa.de/srv/dtick_srv/abo/verify / 1234 (<- aber erst, nachdem ich aboid korrigiert hatte, siehe anderer Fehler) / xxx@xxx.de / HSB
/cygdrive/c/Users/xxx/read_and_save_tickets.sh: line 44: warning: command substitution: ignored null byte in input
/cygdrive/c/Users/xxx/read_and_save_tickets.sh: line 52: jq: command not found
/cygdrive/c/Users/xxx/read_and_save_tickets.sh: line 53: jq: command not found
/cygdrive/c/Users/xxx/read_and_save_tickets.sh: line 55: [: !=: unary operator expected
/cygdrive/c/Users/xxx/read_and_save_tickets.sh: line 61: jq: command not found
Token:
curl: option --compressed: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information
Request error
```

Weißt du da vielleicht eine Möglichkeit, wie ich das auch unter Windows zum Laufen bekomme? Bin leider in Skriptsachen ziemlich unerfahren.

**Comment by fz72** [comment]
So wie ich die Fehlermeldung lese, gibt es unter Windows mit curl die option --compressed nicht.
Hast du die aktuellste Version von curl installiert? Ich hab kurz recherchiert, die aktuelle Version müsste es unterstützen.
"warning: command substitution: ignored null byte in input", kann denke ich ignoriert werden.
Unter Windows muss glaube ich jq erst installiert werden.
https://jqlang.github.io/jq/

**Comment by Paredroi** [comment]
Der behobene Fehler mit der `aboId`, der Tipp mit jq (hab ich in der Windows-Kommandozeile über `winget install jqlang.jq` installiert -> https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-windows-amd64.exe) und schließlich die aktuellste Version 8.7.1 von curl (war wohl in meiner Standardinstallation von Cygwin gar nicht erst enthalten) haben scheinbar erstmal weitergeholfen. Leider aber noch keine Datei erzeugt, da nun die Ausgabe wie folgt aussieht:
```
$ '/cygdrive/c/Users/xxx/read_and_save_tickets.sh'
/cygdrive/c/Users/xxx/read_and_save_tickets.sh: line 18: auth.txt: No such file or directory
Abo Id():1234
Email():xxx@xxx.de
kvpid():HSB
Request: https://deutschlandticket.insa.de/srv/dtick_srv/abo/verify / 1234 / xxx@xxx.de / HSB
 rror: 0 (<- sic!)
```
Nach Blick auf den Quellcode leuchtet mir irgendwie nicht ein, wie diese abgeschnittene Fehlermeldung - und noch dazu mit Ausgabewert 0 - zustande kommt. Mit der Modifikation
```
echo "TEST3"
echo $error_code
echo $error
echo "TEST4"

if [ $error_code != "" ] && [ $error_code != "0" ]
then
	echo "Error:" $error_code" "$error
	exit 1
fi

```
lautet die Ausgabe:
```
TEST3
0

TEST4
 rror: 0
```
Immer noch seltsam. Lasse ich die Fehlerprüfung einfach komplett raus, ergibt sich als Output:
```
Token: eyJhbGciOiJIUzI1[...]9.e[...]Q.6[...]b_J[...]k
jq: parse error: Invalid numeric literal at line 1, column 10
```
Dieser Fehler scheint noch vor Beginn der Schleife aufzutreten. Wenn ich deine auskommentierte $content-Abfrage wieder einkommentiere, erhalte ich noch die zusätzliche Ausgabe:

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>400 Bad Request</title> </head><body> <h1>Bad Request</h1> <p>Your browser sent a request that this server could not understand.<br /> </p> <hr> <address>Apache/2.4.10 (Debian) Server at webapp.insa.de Port 443</address> </body></html>`

Irgendwelche Ideen, was den Fehler beim Parsen angeht?

**Comment by fz72** [comment]
if [ $error_code != "" ] && [ $error_code != "0" ]

Ich denk die 0 wird unter Windows falsch interpretiert. Probier mal diese Ergänzung:
if [ $error_code != "" ] && [ $error_code != "0" ] && [ $error_code != 0 ]

Für mich sieht es eher so aus, als ob der curl Befehl einen Fehler bekommt.
Lass mal das Skript bis zur Stelle laufen, wo du den Token bekommst.

Mit dem kannst du dann den curl-Befehl direkt in der Console ausführen.
Ersetz $token durch den Token, welchen du oben in der Ausgabe erhalten hast:
curl --compressed -sS -H "accept: application/json" -H "x-auth-token: $token"  https://deutschlandticket.insa.de/srv/dtick_srv/abo/load

**Comment by Paredroi** [comment]
Die Ergänzung bzgl. 0 funktioniert leider nicht. Gleiches Ergebnis, wenn ich den dann Quellcode einkommentiert lasse.

Wenn ich den Token direkt versuche einzubetten
```
content=$(curl --compressed -sS -H "accept: application/json" -H "x-auth-token: eyJhbGciOiJIUzI1[...]9.e[...]Q.6[...]b_J[...]k"  https://deutschlandticket.insa.de/srv/dtick_srv/abo/load)
```
erhalte ich als Ausgabe:
```
base64: invalid input
.png8[...]5dcketticket_2024-05-01 00:00:00
```
Da scheint also irgendetwas funktioniert zu haben. Habe mir in der Schleife dann sogar die vier Variablen, nachdem sie mit einem Wert versehen worden sind, erfolgreich ausgeben können per:
```
echo "qrcode: " $qrcode
echo "validfrom: " $validfrom
echo "productname: " $productname
echo "uuid: " $uuid
```
Nur warum wird mir letztlich dann keine Datei erzeugt?

Meine Vermutung war erst, dass es am base64-Befehl lag, weil die Parameter dort mit Hochkommata umgeben waren. Entferne ich sie per `base64 -d <<< $qrcode >> $filename`, erhalte ich aus Output nun keinen Fehler mehr:
```
/cygdrive/c/Users/xxx/read_and_save_tickets.sh: line 120: $filename: ambiguous redirect
.png8[...]5dcketticket_2024-05-01 00:00:00
```
Mit etwas KI-Unterstützung - mir wurde empfohlen, dass ich den Dateiname ganz simpel ohne Leerzeichen erstellen lasse (`filename=$(echo "ticket.png")` - wurde mir dann letztlich unter meinem Cygwin-Pfad (`C:\cygwin64\home\xxx`) endlich eine wunderschöne PNG-Datei mit dem QR-Code erzeugt. Danke für die Unterstützung!

**Comment by Paredroi** [comment]
Vielleicht kannst du der Nachhaltigkeit wegen diese Infos von hier für andere Windows-Benutzer noch in die Beschreibung mit aufnehmen, ich markiert das hier mal als erledigt.

**Comment by fz72** [comment]
Danke! Ich habe in der readme eine Info ergänzt und das Skript um zwei Zeilen ergänzt  um die ungültigen Zeichen zu entfernen.
